blank_issues_enabled: false
contact_links:
  - name: QQ 群 | QQ Group
    url: https://docs.hmcl.net/groups.html
    about: Лаунчер MirWorld 的官方 QQ 交流群。| Офисиальная группа MirWorld.
  - name: Дискорд 服务器 | Дискорд канал
    url: https://discord.gg/jVvC7HfM6U
    about: Лаунчер MirWorld 的官方 Дискорд 服务器。| Официальный Discord-сервер лаунчера MirWorld!
  - name: 其他反馈 | Другие
    url: https://github.com/HMCL-dev/HMCL/discussions/new/choose
    about: 通过 Обсуждения 反馈其他问题。| О других проблемах сообщайте в разделе «Обсуждения».
